---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-backend
  template:
    metadata:
      labels:
        app: vllm-backend
    spec:
      hostIPC: true
      hostNetwork: true
      initContainers:
      - name: init-vllm
        image: vault.habana.ai/gaudi-docker/1.18.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.0:latest
        command: ["hl-smi"]
        env:
        - name: HABANA_VISIBLE_DEVICES
          value: "all"
          #- name: HABANA_VISIBLE_MODULES
          #value: 0,1,2,3
        - name: MODEL
          value: meta-llama/Meta-Llama-3-70B
        resources:
          limits:
            habana.ai/gaudi: 4
            memory: 809Gi
            hugepages-2Mi: 9500Mi
          requests:
            habana.ai/gaudi: 4
            memory: 809Gi
            hugepages-2Mi: 9500Mi

      containers:
      - name: vllm-backend
        image: dockerregistryip:5500/vllm_backend:1.18.0_v1
        workingDir: /vllm-fork
        command:
          - bash
        args:
          - -c
          - '/root/config/run_vllm_backend.sh'
        env:
        - name: MODEL
          value: meta-llama/Meta-Llama-3-70B
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: HF_TOKEN
        - name: HABANA_VISIBLE_DEVICES
          value: "all"
          #- name: HABANA_VISIBLE_MODULES
          #value: "all"
        - name: OMPI_MCA_btl_vader_single_copy_mechanism
          value: none
        - name: VLLM_PROMPT_BS_BUCKET_MIN
          value: "1"
        - name: VLLM_PROMPT_BS_BUCKET_STEP
          value: "32"
        - name: VLLM_PROMPT_BS_BUCKET_MAX
          value: "64"
        - name: VLLM_DECODE_BS_BUCKET_MIN
          value: "1"
        - name: VLLM_DECODE_BS_BUCKET_STEP
          value: "128"
        - name: VLLM_DECODE_BS_BUCKET_MAX
          value: "128"
        - name: VLLM_PROMPT_SEQ_BUCKET_MIN
          value: "128"
        - name: VLLM_PROMPT_SEQ_BUCKET_STEP
          value: "128"
        - name: VLLM_PROMPT_SEQ_BUCKET_MAX
          value: "1024"
        - name: VLLM_DECODE_SEQ_BUCKET_MIN
          value: "128"
        - name: VLLM_DECODE_SEQ_BUCKET_STEP
          value: "128"
        - name: VLLM_DECODE_SEQ_BUCKET_MAX
          value: "2048"
        - name: PT_HPU_LAZY_MODE
          value: "1"
        - name: TENSOR_PARALLEL_SIZE
          value: "4"
        - name: PT_HPU_ENABLE_LAZY_COLLECTIVES
          value: "true"
        - name: VLLM_OVERSCHEDULE
          value: "false"
        - name: VLLM_GRAPH_RESERVED_MEM
          value: "0.2"
            #- name: VLLM_DECODE_BLOCK_BUCKET_STEP
            #  value: "64"
            #- name: VLLM_DECODE_BLOCK_BUCKET_MIN
            #  value: "64"
            #- name: VLLM_OVERSCHEDULE
            #  value: "false"
            #- name: VLLM_GRAPH_RESERVED_MEM
            #  value: "0.2"
            #- name: VLLM_GRAPH_PROMPT_RATIO
            #  value: "0.8"
            
        ports:
        - containerPort: 8000
        resources:
          limits:
            habana.ai/gaudi: 4
            memory: 809Gi
            hugepages-2Mi: 95000Mi
          requests:
            habana.ai/gaudi: 4
            memory: 809Gi
            hugepages-2Mi: 95000Mi

        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /root
        - name: config
          mountPath: /root/config
        - name: dshm
          mountPath: /dev/shm
      volumes:
        - name: config
          configMap:
            name: vllm
            defaultMode: 0500
        - name: data
          #emptyDir: {}
          hostPath:
            path: /fastdata/02/vllm/
            type: Directory
        - name: dshm
          emptyDir:
            medium: Memory
