---
apiVersion: batch/v1
kind: Job
metadata:
  name: vllm-benchmark
spec:
  template:
    spec:
      initContainers:
      - name: init-vllm-benchmark
        image: dockerregistryip:5500/vllm_benchmark:latest
        workingDir: /root
        command:
        - bash
        args:
        - -c
        - 'sleep 120'
        env:
        - name: VLLM_URL
          value: "http://vllm:8000" # Port exposed by the Service
        - name: MODEL
          value: meta-llama/Meta-Llama-3-70B
        volumeMounts:
        - name: data
          mountPath: /root
        - name: config
          mountPath: /root/config

      containers:
      - name: run-generation
        image: dockerregistryip:5500/vllm_benchmark:1.18.0_v1
        workingDir: /root
        command:
          - bash
        args:
          - -c
          - 'config/benchmark.sh'
           #- 'sleep 2000'
        env:
        - name: MODEL
          value: meta-llama/Meta-Llama-3-70B 
        - name: HUGGING_FACE_HUB_TOKEN
          value: hf_TOKEN
        - name: HUGGINGFACE_API_KEY
          value: EMPTY
        - name: OPENAI_API_BASE
          value: "http://vllm:8000/v1"
        - name: OPENAI_API_KEY
          value: EMPTY
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: huggingface-cache
          mountPath: /home/root/.cache/huggingface
        - name: data
          mountPath: /root
        - name: config
          mountPath: /root/config
        - name: dshm
          mountPath: /dev/shm
        imagePullPolicy: Always
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: vllm
            defaultMode: 0500
        - name: data
          #emptyDir: {}
          hostPath:
            path: /fastdata/02/vllm/
            type: Directory
        - name: dshm
          emptyDir:
            medium: Memory
        - name: huggingface-cache
          hostPath:
            path: /home/abi/.cache/huggingface
            type: Directory
