# Created by scalers.ai for Dell

FROM nvcr.io/nvidia/deepstream:6.4-gc-triton-devel

RUN apt-get update && \
    apt install -y python3-gi python3-gst-1.0 python-gi-dev git \
    python3 python3-pip cmake g++ build-essential libglib2.0-dev \
    libglib2.0-dev-bin libgstreamer1.0-dev libtool m4 autoconf automake libgirepository1.0-dev libcairo2-dev \
    libavcodec-dev libavformat-dev libavdevice-dev ffmpeg unzip

RUN wget https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.10/pyds-1.1.10-py3-none-linux_x86_64.whl && \
    python3 -m pip install pyds-1.1.10-py3-none-linux_x86_64.whl

RUN apt-get update && apt-get install -y libglib2.0 libglib2.0-dev \ 
    libjansson4  libjansson-dev librdkafka1 libgstrtspserver-1.0-0 gstreamer1.0-rtsp gobject-introspection gir1.2-gst-rtsp-server-1.0 libgirepository1.0-dev python3-opencv

COPY ./pipeline/requirements.txt requirements.txt
RUN pip3 install --ignore-installed -r requirements.txt
RUN /opt/nvidia/deepstream/deepstream/user_additional_install.sh
COPY ./pipeline /pipeline
WORKDIR /pipeline/
ENTRYPOINT python3 runner.py
