# Created by Scalers AI for Dell Inc.
# Dockerfile to create a container with specific requirements.

FROM python:3.11.6-slim

RUN apt-get update
COPY requirements.txt .

RUN apt-get install build-essential sqlite3 -y
RUN /usr/local/bin/python -m pip install --upgrade pip

RUN pip install -r requirements.txt

COPY src /src

WORKDIR /src

CMD bash run.sh
