{
 "title": "Nodes",
 "tags": [ "node-exporter-mixin" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 }, "options": { "content": "<center> \n<h1>Node 1:XE9680" } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 }, "options": { "content": "<center> \n<h1>Node 2:XE8545" } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 }, "options": { "content": "<center> \n<h1>Node 3:R760xa" } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 }, "options": { "content": "<center> \n<h1>Node 4:R7625" } },
  {
   "title": "Average CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum((1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\", instance=\"192.168.1.112:9100\"}[$__rate_interval])))\r\n/ ignoring(cpu) group_left\r\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"192.168.1.112:9100\"}))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum((1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\", instance=\"192.168.1.101:9100\"}[$__rate_interval])))\r\n/ ignoring(cpu) group_left\r\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"192.168.1.101:9100\"}))*100"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum((1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\", instance=\"192.168.1.108:9100\"}[$__rate_interval])))\r\n/ ignoring(cpu) group_left\r\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"192.168.1.108:9100\"}))*100"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum((1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\", instance=\"192.168.1.121:9100\"}[$__rate_interval])))\r\n/ ignoring(cpu) group_left\r\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"192.168.1.121:9100\"}))*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 -\r\n(\r\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.1.112:9100\"}) /\r\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.1.112:9100\"})\r\n* 100\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 -\r\n(\r\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.1.101:9100\"}) /\r\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.1.101:9100\"})\r\n* 100\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 -\r\n(\r\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.1.108:9100\"}) /\r\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.1.108:9100\"})\r\n* 100\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\r\n(\r\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.1.121:9100\"}) /\r\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.1.121:9100\"})\r\n* 100\r\n)\r\n"
    }
   ]
  },
  {
   "title": "GPU Compute Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{instance=\"192.168.1.112\"})/count (DCGM_FI_DEV_GPU_UTIL{Hostname=\"xe9680\"})"
    }
   ]
  },
  {
   "title": "GPU Compute Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{instance=\"192.168.1.101\"})/count (DCGM_FI_DEV_GPU_UTIL{Hostname=\"xe8545\"})"
    }
   ]
  },
  {
   "title": "GPU Compute Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{instance=\"192.168.1.108\"})/count (DCGM_FI_DEV_GPU_UTIL{instance=\"192.168.1.108\"})"
    }
   ]
  },
  {
   "title": "GPU Compute Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{instance=\"192.168.1.108:9100\"})/count (DCGM_FI_DEV_GPU_UTIL{instance=\"192.168.1.108:9100\"})"
    }
   ]
  },
  {
   "title": "Total GPU Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{instance=\"192.168.1.112\"})/sum(DCGM_FI_DEV_FB_FREE{instance=\"192.168.1.112\"}+DCGM_FI_DEV_FB_USED{instance=\"192.168.1.112\"})*100"
    }
   ]
  },
  {
   "title": "Total GPU Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{instance=\"192.168.1.101\"})/sum(DCGM_FI_DEV_FB_FREE{instance=\"192.168.1.101\"}+DCGM_FI_DEV_FB_USED{instance=\"192.168.1.101\"})*100"
    }
   ]
  },
  {
   "title": "Total GPU Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{instance=\"192.168.1.108\"})/sum(DCGM_FI_DEV_FB_FREE{instance=\"192.168.1.108\"}+DCGM_FI_DEV_FB_USED{instance=\"192.168.1.108\"})*100"
    }
   ]
  },
  {
   "title": "Total GPU Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{instance=\"100.67.115.200\"})/sum(DCGM_FI_DEV_FB_FREE{instance=\"100.67.115.200\"}+DCGM_FI_DEV_FB_USED{instance=\"100.67.115.200\"})*100"
    }
   ]
  }
 ]
}