{
 "title": "TIG_DASH",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GPU Power Consumption %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n    |> range(start: -1d)\r\n    |> filter(fn: (r) => r._measurement == \"gpu_stats\" and r._field == \"power_percent\")\r\n    |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "GPU Temps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n    |> range(start: -1d)\r\n    |> filter(fn: (r) => r._measurement == \"gpu_stats\" and r._field == \"temp\")\r\n    |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Memory Util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n    |> range(start: -1d)\r\n    |> filter(fn: (r) => r._measurement == \"gpu_stats\" and r._field == \"mem_util\")\r\n    |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n    |> range(start: -1d)\r\n    |> filter(fn: (r) => r._measurement == \"gpu_stats\" and r._field == \"fan_speed\")\r\n    |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Power Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n    |> range(start: -1d)\r\n    |> filter(fn: (r) => r._measurement == \"gpu_stats\" and r._field == \"power_used\")\r\n    |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Computation Util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n    |> range(start: -1d)\r\n    |> filter(fn: (r) => r._measurement == \"gpu_stats\" and r._field == \"comp_util\")\r\n    |> yield(name: \"_results\")"
    }
   ]
  }
 ]
}