# Created by Scalers AI for Dell Inc.

FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y  git tar wget
RUN wget https://go.dev/dl/go1.19.4.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.19.4.linux-amd64.tar.gz
ENV PATH="$PATH:/usr/local/go/bin"
ENV GO111MODULE off
COPY src src
WORKDIR src
RUN go get github.com/gin-gonic/gin

CMD bash ./run.sh
